-- Caskade Programming Language Adapter for SQL
-- Created on May 18, 2025
-- By Chris Kelsey of Blue Vision Studios

CREATE OR REPLACE FUNCTION caskade_not(x INTEGER) RETURNS INTEGER AS $$
BEGIN
    RETURN CASE WHEN x = 1 THEN 0 ELSE 1 END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION caskade_and(a INTEGER, b INTEGER) RETURNS INTEGER AS $$
BEGIN
    RETURN CASE WHEN a = 1 AND b = 1 THEN 1 ELSE 0 END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION caskade_or(a INTEGER, b INTEGER) RETURNS INTEGER AS $$
BEGIN
    RETURN CASE WHEN a = 1 OR b = 1 THEN 1 ELSE 0 END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION caskade_eq(a INTEGER, b INTEGER) RETURNS INTEGER AS $$
BEGIN
    RETURN CASE WHEN a = b THEN 1 ELSE 0 END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION caskade_neq(a INTEGER, b INTEGER) RETURNS INTEGER AS $$
BEGIN
    RETURN CASE WHEN a != b THEN 1 ELSE 0 END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION caskade_to_bool(x INTEGER) RETURNS INTEGER AS $$
BEGIN
    RETURN CASE WHEN x = 0 THEN 0 ELSE 1 END;
END;
$$ LANGUAGE plpgsql;
